### Licensed under the same terms as described in the main 
# licensing script of this repository. ###

# ------------------------------
# ---------- FITTINGS ----------
# ------------------------------
water_density:
# - [degC, barrer]
  - []
  - []
  - []

# ------------------------------
# ---------- ANALYSES ----------
# ------------------------------
reservoir_dimensions:
  length: 10.0 # m
  width: 10.0 # m
  height: 10.0 # m
  depth: 100.0 # m

reservoir_conditions:
  temperature: 50.0 # degC
  pressure: 10.0 # bara

fresh_segment:
  volume_fraction: 0.5
  salt_mole_fraction: 0.0

saline_segment:
  salt_mole_fraction: 0.01