### Licensed under the same terms as described in the main 
# licensing script of this repository. ###

# ------------------------------
# ---------- FITTINGS ----------
# ------------------------------
water_density:
# - [degC, kg/m^3]
  - [0.0, 999.840]
  - [1.0, 999.900]
  - [2.0, 999.940]
  - [3.0, 999.970]
  - [4.0, 999.970]
  - [5.0, 999.970]
  - [6.0, 999.940]
  - [7.0, 999.900]
  - [8.0, 999.850]
  - [9.0, 999.780]
  - [10.0, 999.700]
  - [20.0, 998.210]
  - [30.0, 995.650]
  - [40.0, 992.210]
  - [50.0, 988.030]
  - [60.0, 983.190]
  - [70.0, 977.760]
  - [80.0, 971.780]
  - [90.0, 965.300]
  - [100.0, 958.370]


# ------------------------------
# ---------- ANALYSES ----------
# ------------------------------
reservoir_dimensions:
  length: 10.0 # m
  width: 10.0 # m
  height: 10.0 # m
  depth: 100.0 # m

reservoir_conditions:
  temperature: 50.0 # degC
  pressure: 10.0 # bara

fresh_segment:
  volume_fraction: 0.5
  salt_mole_fraction: 0.0

saline_segment:
  salt_mole_fraction: 0.01